server:
  port: 7777
  context-path: /scala-boot

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: cdh
    password: 123456
    url: jdbc:mysql://10.117.130.173:3306/imoocbootscala
  jpa:
   hibernate:
     ddl-auto: update
   database: mysql

